### PR TITLE
Fix formatting on multi line tweets

### PR DESCRIPTION
**Pull request by blha303**
#2

@KenziDK can you check if this fixes the problem?

### CODE REVIEW

**Comment by KDKNFT** [comment]
image

gives the following errors

Unhandled Error
Traceback (most recent call last):
  File "/home/pi/venv/local/lib/python2.7/site-packages/twisted/application/app.py", line 652, in run
    runApp(config)
  File "/home/pi/venv/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/home/pi/venv/local/lib/python2.7/site-packages/twisted/application/app.py", line 386, in run
    self.application = self.createOrGetApplication()
  File "/home/pi/venv/local/lib/python2.7/site-packages/twisted/application/app.py", line 451, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/home/pi/venv/local/lib/python2.7/site-packages/twisted/application/app.py", line 462, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/home/pi/venv/local/lib/python2.7/site-packages/twisted/application/service.py", line 405, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/home/pi/venv/local/lib/python2.7/site-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "/home/pi/Desktop/twittertest/run.py", line 19, in <module>
    config = yaml.load(f.read())
  File "/home/pi/venv/local/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/home/pi/venv/local/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/home/pi/venv/local/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/pi/venv/local/lib/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/pi/venv/local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/pi/venv/local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/pi/venv/local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/pi/venv/local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/pi/venv/local/lib/python2.7/site-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/home/pi/venv/local/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/pi/venv/local/lib/python2.7/site-packages/yaml/parser.py", line 574, in parse_flow_mapping_value
    return self.parse_flow_node()
  File "/home/pi/venv/local/lib/python2.7/site-packages/yaml/parser.py", line 268, in parse_flow_node
    return self.parse_node()
  File "/home/pi/venv/local/lib/python2.7/site-packages/yaml/parser.py", line 371, in parse_node
    token.start_mark)
yaml.parser.ParserError: while parsing a flow node
expected the node content, but found '<stream end>'
  in "<string>", line 11, column 1:

```
^
```

Failed to load application: while parsing a flow node
expected the node content, but found '<stream end>'
  in "<string>", line 11, column 1:

```
^
```

pi@raspberrypi ~ $

**Comment by blha303** [comment]
... There's something wrong with your config, that error isn't relevant to the modified code or indeed the bot at all. :P

**Comment by KDKNFT** [comment]
hahaha I am a fucking idiot

here's what I get with the fixed config

pi@raspberrypi ~ $ tail -f twistd20.log
2015-02-11 12:12:50+0000 [-] Log opened.
2015-02-11 12:12:50+0000 [-] twistd 13.1.0 (/home/pi/venv/bin/python2.7 2.7.3) starting up.
2015-02-11 12:12:50+0000 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2015-02-11 12:12:50+0000 [-] Starting factory <**builtin**.TwitterFactory instance at 0xa8c7d8>
2015-02-11 12:13:00+0000 [TwitterProtocol,client] Getting tweets.
2015-02-11 12:13:00+0000 [TwitterProtocol,client] Starting kenzidk
2015-02-11 12:13:00+0000 [TwitterProtocol,client] [kenzidk] lastid: 563355086391607296
2015-02-11 12:13:00+0000 [TwitterProtocol,client] Rate limit remaining: 172
2015-02-11 12:13:00+0000 [TwitterProtocol,client] Done kenzidk
2015-02-11 12:13:00+0000 [TwitterProtocol,client] ----------
2015-02-11 12:13:00+0000 [TwitterProtocol,client] Traceback (most recent call last):
2015-02-11 12:13:00+0000 [TwitterProtocol,client]   File "/home/pi/venv/local/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 1847, in irc_RPL_WELCOME
2015-02-11 12:13:00+0000 [TwitterProtocol,client]     self.signedOn()
2015-02-11 12:13:00+0000 [TwitterProtocol,client]   File "/home/pi/Desktop/twittertest/run.py", line 67, in signedOn
2015-02-11 12:13:00+0000 [TwitterProtocol,client]     self.loopcall.start(60.0).addErrback(restartloop)
2015-02-11 12:13:00+0000 [TwitterProtocol,client]   File "/home/pi/venv/local/lib/python2.7/site-packages/twisted/internet/task.py", line 173, in start
2015-02-11 12:13:00+0000 [TwitterProtocol,client]     self()
2015-02-11 12:13:00+0000 [TwitterProtocol,client]   File "/home/pi/venv/local/lib/python2.7/site-packages/twisted/internet/task.py", line 218, in **call**
2015-02-11 12:13:00+0000 [TwitterProtocol,client]     d = defer.maybeDeferred(self.f, _self.a, *_self.kw)
2015-02-11 12:13:00+0000 [TwitterProtocol,client] --- <exception caught here> ---
2015-02-11 12:13:00+0000 [TwitterProtocol,client]   File "/home/pi/venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 137, in maybeDeferred
2015-02-11 12:13:00+0000 [TwitterProtocol,client]     result = f(_args, *_kw)
2015-02-11 12:13:00+0000 [TwitterProtocol,client]   File "/home/pi/Desktop/twittertest/run.py", line 93, in getNewTweets
2015-02-11 12:13:00+0000 [TwitterProtocol,client]     out = fmt.format(text="\n".join("\x02{}\x02".format(a) for a in parsemsg(i).split("\n")),
2015-02-11 12:13:00+0000 [TwitterProtocol,client] exceptions.NameError: global name 'parsemsg' is not defined
2015-02-11 12:13:00+0000 [TwitterProtocol,client] Loop crashed: global name 'parsemsg' is not defined

**Comment by blha303** [comment]
Well, that shouldn't happen. Can you paste the whole run.py? Maybe something's different.

**Comment by KDKNFT** [comment]
```
import sys
import re
import urllib2
import json
import random
import unicodedata
import yaml
import subprocess
from pprint import pprint
from time import sleep
from twitter import *
from twisted.internet import reactor, task, defer, protocol
from twisted.python import log
from twisted.words.protocols import irc
from twisted.web.client import getPage
from twisted.application import internet, service

with open('/home/pi/Desktop/twittertest/config.yml') as f:
    config = yaml.load(f.read())
HOST, PORT = config['host'], config['port']


def munge(inp):
    return inp[0] + u"\u200b" + inp[1:]


class TwitterProtocol(irc.IRCClient):
    nickname = config["nickname"]
    username = 'KenziDK'
    versionName = 'Twitter'
    versionNum = 'v1.5'
    realname = 'Tweeting Heroes'
    loopcall = None
    lastid = {}
    try:
        with open('lastid') as f:
            lastid = json.loads(f.read())
    except:
        with open('lastid', 'w') as f:
            f.write(json.dumps(lastid))
            print "Created lastid file"


    def updateLastid(self, sn, id):
        self.lastid[sn] = id
        with open('lastid', 'w') as f:
            f.write(json.dumps(self.lastid))


    def parsemsg(self, msg):
        for i in msg["entities"]["urls"]:
            msg["text"] = msg["text"].replace(i["url"], i["expanded_url"])
        return msg["text"]


    def signedOn(self):
        for channel in self.factory.channels:
            self.join(channel)
        if config["nickserv"]:
            self._send_message("auth " + config["nickserv"], "Q@CServe.quakenet.org")
        def restartloop(reason):
            reason.printTraceback()
            print "Loop crashed: " + reason.getErrorMessage()
            sleep(3)
            self.loopcall.start(60.0).addErrback(restartloop)
        self.loopcall = task.LoopingCall(self.getNewTweets)
        self.loopcall.start(60.0).addErrback(restartloop)
        self._send_message("AUTH HotsTweet *", "Q@CServe.quakenet.org")
        self.mode("HotsTweet", True, "x")

    def getNewTweets(self):
        print "Getting tweets."
        t = Twitter(auth=OAuth(config["oauth-token"],
                               config["oauth-secret"],
                               config["consumer-key"],
                               config["consumer-secret"]))
        for sn in config["twusers"]:
          print "Starting " + sn
          try:
            if sn in self.lastid:
                print "[%s] lastid: %s" % (sn, self.lastid[sn])
                timeline = t.statuses.user_timeline(screen_name=sn,
                                                    since_id=self.lastid[sn],
                                                    count=5,
                                                    exclude_replies=True)
            else:
                timeline = t.statuses.user_timeline(screen_name=sn, count=5,
                                                    exclude_replies=True)
            print "Rate limit remaining: %s" % timeline.headers.getheader('x-rate-limit-remaining')
            timeline.reverse()
            for i in timeline:
                fmt = u"\x02{screen_name}\x02: {text} [ https://twitter.com/{screen_name}/status/{id} ]"
                out = fmt.format(text="\n".join("\x02{}\x02".format(a) for a in parsemsg(i).split("\n")),
                                screen_name=sn,
                                id=i["id_str"])
                print "Sending " + out
                try:
                    self._send_message(out.encode('utf-8'), config["twusers"][sn])
                except:
                    print "Couldn't send %s due to error"
                self.updateLastid(sn, i["id_str"])
          finally:
            print "Done " + sn
            print "----------"

    def privmsg(self, user, channel, message):
        nick, _, host = user.partition('!')
        try:
            key = (key for key,value in config["twusers"].items() if value.lower()==channel.lower()).next()
        except StopIteration:
            key = None
        split = message.split(" ")
        if message == "!restart" and nick == config["owner"]:
            subprocess.Popen(['/home/pi/Desktop/twittertest/restart.sh'])

    def _send_message(self, msg, target, nick=None):
        if nick:
            msg = '%s, %s' % (nick, msg)
        self.msg(target, msg)

    def _show_error(self, failure):
        return failure.getErrorMessage()





class TwitterFactory(protocol.ReconnectingClientFactory):
    protocol = TwitterProtocol
    channels = config["twusers"].values()

if __name__ == '__main__':
    reactor.connectTCP(HOST, PORT, TwitterFactory())
    log.startLogging(sys.stdout)
    reactor.run()

elif __name__ == '__builtin__':
    application = service.Application('Twitter')
    ircService = internet.TCPClient(HOST, PORT, TwitterFactory())
    ircService.setServiceParent(application)
```

**Comment by blha303** [comment]
Ah, well, you're missing `def parsemsg` :P That'd explain your error. Again, it isn't a problem with the commit itself :P I'll just assume it works and merge it.

**Comment by KDKNFT** [comment]
```
def parsemsg(self, msg):
    for i in msg["entities"]["urls"]:
        msg["text"] = msg["text"].replace(i["url"], i["expanded_url"])
    return msg["text"]
```

it's there isn't it? :P

**Comment by blha303** [comment]
Then you have to change the reference in your script to self.parsemsg xD

**Pull request merged**
